project_name: sbomex

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - id: binaries
    binary: sbomex-{{ .Os }}-{{ .Arch }}
    main: .
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env:
      - CGO_ENABLED=0
    no_unique_dist_dir: true
    ignore:
      - goos: windows
        goarch: arm64

nfpms:
  - id: sbomex
    package_name: sbomex
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Interlynk
    homepage: https://interlynk.io
    maintainer: Interlynk Authors hello@interlynk.io
    builds:
      - binaries
    description: Find & pull public SBOMs
    license: "Apache License 2.0"
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: /usr/bin/sbomex-{{ .Os }}-{{ .Arch }}
        dst: /usr/bin/sbomex
        type: "symlink"

archives:
- format: binary
  name_template: "{{ .Binary }}"
  allow_different_binary_count: true

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow
  draft: true
