project_name: sbomex

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    
gomod:
  proxy: true 

builds:
  - id: binaries 
    binary: sbomex-{{ .Os }}-{{ .Arch }}
    main: .
    flags:
      - -trimpath 
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - windows
      - darwin 
    goarch:
      - arm64
      - amd64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env:
      - CGO_ENABLED=0
    no_unique_dist_dir: true
    overrides:
      - env:
         - CGO_ENABLED=1
archives:
- format: binary
  name_template: "{{ .Binary }}"
  allow_different_binary_count: true 

snapshot: 
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow 
  draft: true 