name: releaser

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  releaser:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3 
        with:
          fetch-depth: 0
      - run: git fetch --force --tags 
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
          check-latest: true
          cache: true
      - name: Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true 
      - run: go version
      - run: goreleaser -v 
      - name: Releaser
        run: make release  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     overrides:
      - goos: darwin
        goarch: arm64
        goamd64: v1
        env:
          - CGO_ENABLED=1